### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by archoversight** [Yubico/u2fval#43]
Hello,

I wanted to double check and see if this project is still being maintained or if effort should be spent elsewhere to replace the functionality that this project provides?

I am working on some patches to add some behaviors that are required for a project at $WORK, and I wanted to understand better if the patches would be accepted upstream or not before I go make them.

Thanks!

**Comment by dainnilsson** [comment]
Hi,

This project is not being actively maintained and for anyone looking at it I would strongly recommend implementing WebAuthn rather than U2F. We offer libraries to make this easier, such as python-fido2 and java-webauthn-server, but no standalone server at the moment.

I'll update the README to clarify the state.
